server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/authority_user?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=55555
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

## Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

security.jwt.secret-key=512bbed018a40c3528db4fe270df30477bcf5b2e315dbe33249743911f46922f
security.jwt.expiration-time=7200000